### PR TITLE
Protocol18

### PR DESCRIPTION
**Pull request by HunterNyan**

### CODE REVIEW

**Comment by DASPRiD** [comment]
Why did you close it again?

**Comment by HunterNyan** [comment]
It's not quite complete yet :) got a few more things to do before I send it back your way.

**Comment by DASPRiD** [comment]
Ah, that's fine :)

**Comment by DASPRiD** [comment]
@HunterNyan Did you ever manage to finish this? :)

**Comment by HunterNyan** [comment]
Unfortunately not, it kinda lost it's purpose for us so I never got anywhere further.

**Pull request closed without merging**
